# @package _global_

# Mirror `scale_decode` - pretrain a stable decoder, while varying the unsup source
# Tag refers to unsup source

defaults:
  - /model: flat_enc_dec
  - /model/task:
    - joint_bhvr_decode_flat
  - /dataset: flat
dataset:
  eval_ratio: 0.5
  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel

  datasets:
  - observation_.*
  exclude_datasets:
  - closed_loop.*
  - observation_CRS08_.*
  # No eval.
  z_score: 'kin_zscore.pt'
model:
  causal: true
  neurons_per_token: 32
  decoder_context_integration: 'cross_attn'
  task:
    decode_time_pool: ""
    task_weights: [1.0, 0.1]
    mask_ratio: 0.5
    behavior_lag: 0 # No lag for human data. For parity with ongoing exps.
    decode_normalizer: ""
  val_iters: 5
  lr_ramp_steps: 50
train:
  patience: 50
inherit_exp: pitt_v3