# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - observation_.*
  - odoherty_rtt-Indy.*
  odoherty_rtt:
    chop_size_ms: 2500
    include_sorted: False
    arrays: ['Indy-M1', 'Loco-M1']
train:
  autoscale_batch_size: false
  batch_size: 64
model:
  task:
    mask_ratio: 0.5
inherit_tag: human_10l
