# @package _global_
defaults:
  - /model: flat_enc_dec
  - /dataset: flat
dataset:
  max_channels: 288
  neurons_per_token: 32
  datasets:
  - odoherty_rtt-Indy.*
  eval_datasets:
  - odoherty_rtt-Indy-20160407_02 # First indy session
  - odoherty_rtt-Indy-20160627_01 # Original
  - odoherty_rtt-Indy-20161005_06
  - odoherty_rtt-Indy-20161026_03
  - odoherty_rtt-Indy-20170131_02 # Last indy sesison
model:
  causal: true
  task:
    mask_ratio: 0.5
  neurons_per_token: 32
train:
  patience: 100
  autoscale_batch_size: false
  batch_size: 128
seed: 3