# @package _global_
defaults:
  - _default
train:
  autoscale_batch_size: True
#   autoscale_batch_size: False
  batch_size: 32
  patience: 200
dataset:
  augmentations:
  - rand_crop_time # preset to crop to 1s
  datasets:
  - observation_CRS08.*
  - fbc_CRS08.*
  exclude_datasets:
  - CRS08_13.* # This was an NDT experiment set
  - CRS08_14.* # This was all imported as unstructured
  - CRS08_15.* # All imported as unstructured
  - CRS08_16.* # NDT2 experiment set
model:
  # FT-ing
  val_iters: 10
  task:
    mask_ratio: 0.1
inherit_exp: pitt_v3/decode_no_bounds
inherit_tag: human_aug_full
# inherit_tag: human_10l