# @package _global_
defaults:
  - _default
train:
  autoscale_batch_size: false
  batch_size: 128 # 40G
  accumulate_batches: 2
dataset:
  augmentations:
  - rand_crop_time # preset to crop to 1s
model:
  task:
    mask_ratio: 0.1
inherit_tag: human_10l