# @package _global_
defaults:
  - _default
train:
  autoscale_batch_size: False
  batch_size: 32
  patience: 200
dataset:
  augmentations:
  - rand_crop_time # preset to crop to 1s
  datasets:
  - observation_CRS02b_1959.*
  exclude_datasets: []
  behavior_dim: 8
model:
  task:
    mask_ratio: 0.1
    decode_normalizer: ""
inherit_tag: human_10l