# @package _global_
defaults:
  - _default
train:
  autoscale_batch_size: false
  batch_size: 16 # being run on A100 with 80G memory. No need for multinode.
  # batch_size: 256 # being run on A100 with 80G memory. No need for multinode.
  accumulate_batches: 8
dataset:
  datasets:
  - observation_.*
  exclude_datasets: []
  behavior_dim: 8
model:
  task:
    tasks:
    - ModelTask.shuffle_infill
    - ModelTask.kinematic_decoding
    mask_ratio: 0.1
    decode_normalizer: ''
    covariate_mask_ratio: 0.4 # TODO test 0.5 for symmetry errors...
inherit_tag: human_10l