# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - odoherty_rtt.*
  z_score: 'kin_zscore.pt'
  augmentations:
  - rand_crop_time # preset to crop to 1s
train:
  autoscale_batch_size: false
  batch_size: 64
model:
  task:
    decode_normalizer: ""
    behavior_lag: 120
inherit_tag: human_10l

# RTT Pitt Init legacy