# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - odoherty_rtt.*
  z_score: 'kin_zscore.pt'
  augmentations:
  - rand_crop_time # preset to crop to 1s
train:
  autoscale_batch_size: false
  batch_size: 128 # being run on A100 with 80G memory. No need for multinode.
  # batch_size: 256 # being run on A100 with 80G memory. No need for multinode.
model:
  task:
    tasks:
    - ModelTask.shuffle_infill
    - ModelTask.kinematic_classification
    decode_normalizer: ""
    mask_ratio: 0.1
inherit_tag: human_10l