# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - observation_CRS07.*
  exclude_datasets:
  - observation_CRS07_15.*
  - observation_CRS07_16.*
train:
  autoscale_batch_size: false
  batch_size: 64
model:
  task:
    mask_ratio: 0.5
inherit_tag: crs07