# @package _global_
defaults:
  - _default
dataset:
  datasets:
  - observation_.*
  - odoherty_rtt.*
  odoherty_rtt:
    chop_size_ms: 2500
    include_sorted: False
    arrays: ['Indy-M1', 'Loco-M1']
  z_score: 'kin_zscore.pt'
  augmentations:
  - rand_crop_time # preset to crop to 1s
train:
  autoscale_batch_size: false
  batch_size: 64
model:
  task:
    mask_ratio: 0.5
    decode_normalizer: ""
    behavior_tolerance: 0.1
inherit_tag: human_10l

# RTT Pitt Init legacy