# @package _global_
defaults:
- _default

dataset:
  pitt_co:
    chop_size_ms: 1000
  tokenize_covariates: True
  semantic_positions: True
model:
  task:
    covariate_blacklist_dims: [0, 1, 2, 3, 4, 5, 6, 7]
train:
  autoscale_batch_size: true
  batch_size: 256 # 80G
  effective_batch_size: 1024
