# @package _global_

defaults:
  - _default
model:
  task:
    tasks:
    - ModelTask.spike_infill
    - ModelTask.kinematic_infill
    - ModelTask.constraints
    - ModelTask.return_context
    task_weights: [1.0, 1.0, 0., 0.]
dataset:
  max_tokens: 16384 # For subsequent curricula
  datasets:
  - churchland.*
  - gallego.*
  - dyer_co.*
  - miller.*
  - odoherty_rtt.*
  - delay.*
  - pitt_broad.*
train:
  batch_size: 4
load_from_id: pitt_monkey_4k-srki6nfg