# @package _global_

defaults:
  - _default
model:
  lr_decay_steps: 15000
  task:
    tasks:
    - ModelTask.spike_infill
    - ModelTask.kinematic_infill
    - ModelTask.constraints
    - ModelTask.return_context
    task_weights: [1.0, 1.0, 0., 0.]
dataset:
  datasets:
  - churchland.*
  # - gallego.*
  - dyer_co.*
  # - miller.*
  # - odoherty_rtt.*
  - delay.*
  # - pitt_broad.*

  # Include eval dataset - CRS08 etc

  eval_datasets: []
train:
  batch_size: 32 # 40G
  patience: 50