# @package _global_
# Updated to direct ICL experiments. No pretraining, for simplicity.
defaults:
  - /model:
    - flat_enc_dec
    - scale_history
    # - largescale
  - /model/task:
    - decode_flat_v2
  - /dataset:
    - flat
    - scale_history
  - /train:
    - midscale
model:
  next_step_prediction: True
  token_maskout: 0.8
  task:
    tasks:
    - ModelTask.spike_context
    - ModelTask.kinematic_infill
    - ModelTask.constraints
    - ModelTask.return_context
    task_weights: [0., 1.0, 0., 0.]
    metrics:
    - Metric.kinematic_r2
    - Metric.kinematic_acc
    encode_constraints: True
    use_constraint_cls: False # No need
  transformer:
    n_layers: 6
    max_trial_length: 1500 # Up to 30s
  use_full_encode: True
  decoder_context_integration: 'cross_attn' # Literally not even used
dataset:
  max_length_ms: 15000
  max_trial_length: 1500
  odoherty_rtt:
    chop_size_ms: 15000
  pitt_co:
    chop_size_ms: 15000

  tokenize_covariates: True
  sparse_constraints: True
  behavior_dim: 10 # Force is here, include +1 for padding, etc.
  datasets: [] # To be overridden
  data_keys:
  - DataKey.spikes
  - DataKey.constraint
  - DataKey.bhvr_vel
  - DataKey.task_return
train:
  autoscale_batch_size: true
  batch_size: 4 # 40G
