# @package _global_
defaults:
  - _default
  - /model/task:
    - decode_flat_v2 # spcify individually
dataset:
  max_channels: 160
  max_arrays: 2
  datasets:
  - churchland_maze_jenkins.*
  # - 'churchland_maze_jenkins-0'
