# @package _global_

defaults:
  - _default

  - /model:
    - largescale
  - /model/task:
    - decode_flat_v2
model:
  lr_ramp_steps: 25
  next_step_prediction: True
  token_maskout: 0.8
  task:
    tasks:
    - ModelTask.spike_context
    - ModelTask.kinematic_infill
    - ModelTask.constraints
    - ModelTask.return_context
    task_weights: [0., 1.0, 0., 0.]
    metrics:
    - Metric.kinematic_r2
    - Metric.kinematic_acc
    encode_constraints: True
    use_constraint_cls: False # No need
  transformer:
    n_layers: 6
    max_trial_length: 1500 # Up to 30s
    n_heads: 8
  hidden_size: 1024
  use_full_encode: True
  decoder_context_integration: 'cross_attn' # Literally not even used
dataset:
  datasets:
  # All cropped trialized data, but ~100K trials.
  - churchland.*
  - gallego.*
  - dyer_co.*
  # - miller.*
  # - odoherty_rtt.* # Not that suitable because dramatically different length atm
  max_channels: 224 # 211
  max_arrays: 2
train:
  batch_size: 24 # 80G
  patience: 50
load_from_id: monkey_trialized_6l_1024-22lwlmk7
