# @package _global_
defaults:
  - _default
model:
  task:
    tasks: [ModelTask.spike_context, ModelTask.kinematic_decoding, ModelTask.return_context]
    # covariate_mask_ratio: 1.0
dataset:
  sparse_rewards: True
inherit_tag: sparse
train:
  autoscale_batch_size: False
  batch_size: 8 # always OOM and regardless of training steps # (pretrain 4 gpus), yikes, 16 is too high