# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - _default
model:
  causal: true
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 8
  decoder_context_integration: 'cross_attn'
  task:
    decode_time_pool: ""
  decoder_layers: 1
train:
  batch_size: 16
  accumulate_batches: 4
inherit_tag: f8