# @package _global_

defaults:
- _default
dataset:
  max_length_ms: 15000
  max_trial_length: 1500
  odoherty_rtt:
    chop_size_ms: 15000
  # datasets:
  # - odoherty_rtt-Indy.*
model:
  transformer:
    max_trial_length: 1500
  session_embed_strategy: EmbedStrat.none
  task:
    tasks:
    - ModelTask.spike_context
    - ModelTask.kinematic_classification
    covariate_mask_ratio: 0.2 # Target - last 2s
    context_prompt_time_thresh: 400 # 8s * 50Hz
train:
  autoscale_batch_size: False
  batch_size: 32
  effective_batch_size: 512 # 4x 80G
  patience: 150
inherit_tag: 30s
notes: "Remove ICL aspect, for sake of regression testing, and for sake of turning into straight regression problem."
