# @package _global_

defaults:
- _default
dataset:
  max_length_ms: 30000
  max_trial_length: 1500
  odoherty_rtt:
    chop_size_ms: 30000
model:
  transformer:
    max_trial_length: 1500
  # session_embed_strategy: EmbedStrat.none
train:
  autoscale_batch_size: False
  batch_size: 8
  effective_batch_size: 128
notes: "Just for comparison"