# @package _global_

defaults:
- _default
dataset:
  max_length_ms: 30000
  max_trial_length: 1500
  odoherty_rtt:
    chop_size_ms: 30000
  # datasets:
  # - odoherty_rtt-Indy.*
model:
  transformer:
    max_trial_length: 1500
  session_embed_strategy: EmbedStrat.none
  task:
    covariate_mask_ratio: 1.0 # Straight regression
    context_prompt_time_thresh: 0
train:
  autoscale_batch_size: False
  batch_size: 8
  effective_batch_size: 128
  patience: 150
inherit_tag: 30s
notes: "Remove ICL aspect, for sake of regression testing, and for sake of turning into straight regression problem."