# @package _global_
defaults:
  # - _default
  - /model:
    - flat_enc_dec
    # - scale_history
  - /dataset:
    - flat
    # - scale_history
model:
  session_embed_token_count: 1 # Keep it low for maybe easier FT?
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
  causal: True
  task:
    mask_ratio: 0.5
    encode_constraints: True

  transformer:
    n_layers: 8
dataset:
  datasets:
  - pitt_broad.*
  data_keys:
  - DataKey.spikes
  - DataKey.active_assist
  - DataKey.passive_assist
  - DataKey.brain_control
train:
  autoscale_batch_size: true
  effective_batch_size: 512
