# @package _global_
defaults:
  # - _default
  - /model:
    - flat_enc_dec
    - scale_history
  - /dataset:
    - flat
    - scale_history
model:
  session_embed_token_count: 1 # Keep it low for maybe easier FT?
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
  causal: True
  task:
    mask_ratio: 0.5
  transformer:
    n_layers: 8
dataset:
  pitt_co:
    chop_size_ms: 2500
  datasets:
  - observation.*
  - fbc.*
  exclude_datasets:
  - pitt_broad.*
train:
  autoscale_batch_size: true
  effective_batch_size: 512
