# @package _global_
# Updated to direct ICL experiments. No pretraining, for simplicity.
defaults:
  - /model:
    - flat_enc_dec
    - scale_history
    - largescale
  - /model/task:
    - decode_flat_v2
  - /dataset:
    - flat
    - scale_history
  - /train:
    - largescale
model:
  task:
    tasks: [ModelTask.spike_context, ModelTask.kinematic_classification, ModelTask.constraints]
    task_weights: [0., 1.0]
    covariate_mask_ratio: 0.4
    context_prompt_time_thresh: 450 # 9s * 50Hz, 6s target
    encode_constraints: True
  transformer:
    max_trial_length: 1500 # Up to 30s
  use_full_encode: True
  decoder_context_integration: 'cross_attn'
dataset:
  max_length_ms: 15000
  max_trial_length: 1500
  odoherty_rtt:
    chop_size_ms: 15000
  pitt_co:
    chop_size_ms: 15000

  tokenize_covariates: True
  sparse_constraints: True
  behavior_dim: 10 # Force is here, include +1 for padding, etc.
  datasets:
  - pitt_broad.* # Currently has obs, fbc, helicopter rescue; i.e. this was a repull of NDT2 `pitt_co` criteria, the script for pulling might no longer exist. I also don't think this has ortho.
  data_keys:
  - DataKey.spikes
  - DataKey.constraint
  - DataKey.bhvr_vel
  - DataKey.task_return
train:
  patience: 50
  autoscale_batch_size: true
  batch_size: 2 # 40G
