# @package _global_
defaults:
  - _default
model:
  hidden_size: 512
  transformer:
    n_layers: 6
  task:
    tasks: [ModelTask.spike_context, ModelTask.kinematic_decoding, ModelTask.constraints, ModelTask.return_context]
dataset:
  sparse_rewards: True
notes: "Add return"