# @package _global_
defaults:
  - _default
model:
  hidden_size: 512
  transformer:
    n_layers: 6
  task:
    tasks: [ModelTask.spike_context, ModelTask.kinematic_classification, ModelTask.constraints, ModelTask.return_context]
dataset:
  sparse_rewards: True
# train:
  # strategy: "deepspeed_stage_2" # well, this is dumb, doesn't improve max batch size.
notes: "Add return"