# @package _global_

defaults:
  - _default
model:
  kinematic_token_maskout: 0.0
  task:
    tasks:
    - ModelTask.spike_infill
    - ModelTask.kinematic_infill
    - ModelTask.constraints
    - ModelTask.return_infill
    task_weights: [1.0, 1.0, 0., 1.0]
    metrics:
    - Metric.kinematic_r2
    - Metric.kinematic_acc
    - Metric.return_acc
dataset:
  max_tokens: 4092 # For subsequent curricula
train:
  batch_size: 24 # 40G