# @package _global_

defaults:
  - _default
model:
dataset:
  max_tokens: 4092 # For subsequent curricula
  datasets:
  # - churchland.*
  # - gallego.*
  # - dyer_co.*
  # - miller.*
  # - odoherty_rtt.*
  # - delay.*
  - pitt_broad_pitt_co_CRS02bLab_1.*
train:
  batch_size: 32