defaults:
  - /model: flat_enc_dec
  - /model/task:
    - bhvr_decode_flat
  - /dataset: flat
  - /train: single_session_exp1
dataset:
  datasets:
  - dummy.datafiles

  data_keys:
  - DataKey.spikes
  - DataKey.bhvr_vel
model:
  accelerate_new_params: 10.0
  lr_schedule: 'fixed'
train:
  autoscale_batch_size: false
  batch_size: 4
  patience: 50
init_ckpt: '{shared_dir}/pretrained/pretrained_human_monkey.pt'

tag: 'online_finetune'
experiment_set: 'online_bci'
notes: "Closed loop decoder human and monkey (joint prep)"