# @package _global_

defaults:
  - _default
model:
  extra_task_embed_ckpt: '{shared_dir}/pretrained/human_fbc.ckpt' # perks of fbc base.
init_ckpt: '{shared_dir}/pretrained/human_fbc.ckpt'
tag: 'online_fbc_tune'
notes: "Decoder base: human obs, ortho, fbc." # pitt_v3/decode_full/human_fbc