# @package _global_

defaults:
  - /model: flat_enc_dec
  - /dataset: flat
  - /train: single_session_exp1
model:
  hidden_size: 128 # size down appropriately
  causal: true
  subject_embed_strategy: EmbedStrat.token
  task:
    mask_ratio: 0.5 # for efficiency
  neurons_per_token: 32
dataset:
  eval_ratio: 0.1
  eval_split_continuous: True
  scale_limit_per_eval_session: 320
  datasets:
  - odoherty_rtt-Indy-20160627_01 # Original
  eval_datasets:
  - odoherty_rtt-Indy-20160627_01 # Original
train:
  autoscale_batch_size: true
fragment_datasets: False