# @package _global_

defaults:
  - _default
model:
  task: # Fine tune like you pretrain..
    tasks:
    - ModelTask.spike_infill
    - ModelTask.kinematic_infill
    - ModelTask.constraints
    - ModelTask.return_context
    task_weights: [1.0, 1.0, 0., 0.]
dataset:
  # scale_limit_per_eval_session: 100 # 500s, over 24 sessions = 200 minutes of data over 24 sessions.

  scale_limit_per_eval_session: 160 # 500s, over 24 sessions = 200 minutes of data over 24 sessions.
  eval_ratio: 0.25 # We don't have enough to learn anything :(
inherit_tag: neural_data_monkey-pitt
