# @package _global_

defaults:
  - _default
# init_ckpt: '{shared_dir}/pretrained/human_obs.ckpt'
inherit_exp: pitt_v3/decode_no_bounds
inherit_tag: human_aug_only_full # etc
tag: 'online_obs_tune'
notes: "Decoder base: human obs." # pitt_v3/decode_full/human
model:
  closed_loop_crop_bins: 75