# @package _global_

defaults:
  - _default
dataset:
  datasets:
  - observation_CRS08_0_0
  # - observation_CRS02b_1953_2
  # - observation_CRS02b_1953_9
  # - observation_CRS02b_0_0
  # augmentations:
  # - rand_crop_time # preset to crop to 1s
  eval_datasets: []
  # - observation_CRS08_0_0
  # - observation_CRS02b_1953_2
  # - observation_CRS02b_1953_9
  # eval_ratio: 0.1 # adopt this so we can use pitt_decode script
model:
  task:
    mask_ratio: 0.1
    # mask_ratio: 0.5
  # extra_task_embed_ckpt: '{shared_dir}/pretrained/human_fbc.ckpt' # perks of fbc base. Irrelevant though.
  closed_loop_crop_bins: 50
# inherit_exp: pitt_v3/decode_no_bounds
# inherit_tag: human_m5
inherit_exp: pitt_v3/decode_online_bci
# inherit_tag: human_m25
inherit_tag: human_aug_m25
# inherit_tag: human_aug_m1
tag: 'online_test_tune'
notes: "Decoder base: human obs, ortho, fbc."