# @package _global_

defaults:
  - _default
# init_ckpt: '{shared_dir}/pretrained/human_obs.ckpt'
inherit_exp: pitt_v3/decode_online_bci # JY TODO replace with pitt_v3/decode_online_bci
# inherit_exp: pitt_v3/decode_no_bounds # JY backup, not clear on lineage here
inherit_tag: human_aug_m1 # JY TODO replace with human_aug_m5 or human_aug_m1, with or without respect, whichever is better offline
# inherit_tag: human_aug_only_full # JY backup, not clear on lineage here
tag: 'online_obs_tune_m1_m1'
notes: "Decoder base: human obs." # pitt_v3/decode_full/human
model:
  closed_loop_crop_bins: 50
  task:
    mask_ratio: 0.1