# @package _global_

defaults:
  - _default
inherit_exp: pitt_v3/decode_online_bci
inherit_tag: human_crs08_tune
tag: 'online_human_pt'
notes: "Supervised tuning of human-pt model."
model:
  closed_loop_crop_bins: 50 # safe default.

# Note, if you plan on using multisession, then specify: dataset.datasets=['observation_CRS08.*'] (this will integrate the new session automatically)