# @package _global_

defaults:
  - _default
init_ckpt: '{shared_dir}/pretrained/human_obs.ckpt'
tag: 'online_obs_tune_m5_m5'
notes: "Decoder base: human obs." # pitt_v3/decode_full/human
model:
  closed_loop_crop_bins: 50