# @package _global_
defaults:
  - _default
dataset:
  datsets:
  - observation_CRS07_15.*
  - observation_CRS07_16.*
  eval_datasets:
  - observation_CRS07_15.*
  - observation_CRS07_16.*
model:
  task:
    mask_ratio: 0.5