# @package _global_
defaults:
  - _default
dataset:
  z_score: 'kin_zscore.pt'
train:
  autoscale_batch_size: false
  batch_size: 32
  accumulate_batches: 2
model:
  transformer:
    n_layers: 16
  task:
    mask_ratio: 0.5
    decode_normalizer: ""
