# @package _global_
defaults:
  - _default
model:
  task:
    encode_constraints: False
    use_constraint_cls: False
dataset:
  sparse_constraints: True
inherit_tag: sparse_constraint
# load_from_id: no_constraint-wpqn6aly