# @package _global_
defaults:
  - _default
model:
  task:
    encode_constraints: False
    use_constraint_cls: False
    covariate_mask_ratio: 1.0
dataset:
  sparse_constraints: True
inherit_tag: sparse_constraint
train:
  batch_size: 16 # always OOM and regardless of training steps # (pretrain 4 gpus)
