# @package _global_
defaults:
  - _default
model:
  task:
    tasks: [ModelTask.spike_context, ModelTask.kinematic_decoding, ModelTask.constraints]
    encode_constraints: True
    use_constraint_cls: True
    decode_tokenize_dims: True
dataset:
  sparse_constraints: True
inherit_tag: sparse_constraint_enc
train:
  batch_size: 8 # always OOM and regardless of training steps # (pretrain 4 gpus), yikes, 16 is too high
