# @package _global_
defaults:
  - _default
dataset:
  data_keys: [DataKey.spikes, DataKey.bhvr_vel]
  datasets:
  - observation.*
train:
  autoscale_batch_size: false
  batch_size: 128
# There are about 20K obs trials in the latest poll.