# @package _global_
defaults:
  - _default
model:
  transformer:
    n_layers: 10
dataset:
  datasets:
  - observation_.* # pursuit.*
  - ortho_.* # pursuit.*
  - fbc_.* # pursuit.*
  - unstructured_.*
  - pitt_co.*
  # Our "test set"

train:
  autoscale_batch_size: false
  batch_size: 64
  accumulate_batches: 4
