# @package _global_
defaults:
  - /model:
    - flat_enc_dec
  - /dataset: flat
model:
  session_embed_token_count: 1 # Keep it low for maybe easier FT?
  subject_embed_strategy: EmbedStrat.token
  task_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
  causal: True
  task:
    mask_ratio: 0.5
  transformer:
    n_layers: 8
dataset:
  datasets:
  - observation_.*
  - fbc_.*
train:
  patience: 250
  autoscale_batch_size: false
  batch_size: 256
