# @package _global_
defaults:
  - /model:
    - flat_enc_dec
    - scale_history
  - /model/task:
    - joint_decode_flat_v2
  - /dataset:
    - flat
    - scale_history
model:
  session_embed_token_count: 1 # Keep it low for maybe easier FT?
  subject_embed_strategy: EmbedStrat.token
  neurons_per_token: 32
  causal: True
  task:
    mask_ratio: 0.2
    covariate_mask_ratio: 0.5
  transformer:
    n_layers: 8
dataset:
  tokenize_covariates: True
  behavior_dim: 8
  sparse_constraints: True
  datasets:
  - pitt_return.* # Currently has obs, ortho, fbc, helicopter rescue
  # - pitt_broad.*
  data_keys:
  - DataKey.spikes
  - DataKey.constraint
  - DataKey.bhvr_vel # Just testing
  # - DataKey.task_return
train:
  patience: 50
  autoscale_batch_size: true
  effective_batch_size: 512
