# @package _global_
defaults:
  - _default
model:
  task:
    tasks: [ModelTask.shuffle_infill]
    context_prompt_time_thresh: 100
dataset:
  tokenize_covariates: True
  # sparse_rewards: True
train:
  batch_size: 16