# @package _global_
defaults:
  - _default
model:
  next_step_prediction: True
  task:
    tasks: [ModelTask.spike_context, ModelTask.kinematic_infill, ModelTask.constraints, ModelTask.return_context]
    task_weights: [0., 1., 0., 0.]
    decode_quantize_classes: 512
  hidden_size: 1024
  transformer:
    n_layers: 12
    n_heads: 8
  kinematic_token_maskout: 0.8
dataset:
  sparse_rewards: True
  datasets:
  - miller.*
  - pitt_broad.* # Currently has obs, fbc, helicopter rescue; i.e. this was a repull of NDT2 `pitt_co` criteria, the script for pulling might no longer exist. I also don't think this has ortho.
  - odoherty_rtt-Loco.* # We'll eval with Indy
train:
  batch_size: 16 # 80G
load_from_id: bhvr_12l_1024_km8_c512-6p6h9m7l