# @package _global_

defaults:
  - _default
model:
  task:
    spike_loss: cross_entropy
    prefix_ratio: 1.0
    context_prompt_time_thresh: -750 # 15s

    constraint_mute: True
    return_mute: True
dataset:
  sparse_rewards: False
train:
  batch_size: 32
notes: "40M dense reward"