# @package _global_

defaults:
  - _default
dataset:
  max_tokens: 4092 # For subsequent curricula
  datasets:
  # - churchland.*
  - gallego.*
  - dyer_co.*
  - rouse.*
  - flint.*
  - miller.*
  - delay.*
  - odoherty_rtt.*
  # - delay.*
  # - pitt_broad.*
train:
  batch_size: 32