# @package _global_

defaults:
  - _default
model:
  lr_decay_steps: 5000
dataset:
  datasets:
  - odoherty_rtt-Indy.*
  - dyer_co_chewie_2 # Low resource task. Only 1 other session given.
  - miller_Jango-Jango_20150730_001
  - miller_Jango-Jango_20150731_001
  - miller_Jango-Jango_20150801_001
  - miller_Jango-Jango_20150805_001
train:
  batch_size: 32 # 40G
  patience: 50
  effective_batch_size: 512