# @package _global_

defaults:
  - _default
model:
  lr_decay_steps: 5000
dataset:
  datasets:
  # All cropped trialized data, but ~100K trials.
  # - churchland.*
  # - gallego.*
  - rouse.*
  # - miller.*
  # - odoherty_rtt.*
  # - delay.*
  rouse:
    chop_size_ms: 5000
train:
  batch_size: 32 # 40G
  # batch_size: 64 # 80G
  patience: 50
  effective_batch_size: 2048
  # effective_batch_size: 8192
