# @package _global_

# Mirror `scale_decode` - pretrain a stable decoder, while varying the unsup source
# Tag refers to unsup source

defaults:
  - _default
dataset:
  datasets:
  - observation_.*
  - fbc_.*
model:
  task:
    decode_tokenize_dims: True
    # covariate_blacklist_dims: [0,3,4,5]
    covariate_mask_ratio: 0.4
train:
  autoscale_batch_size: false
  accumulate_batches: 2
  batch_size: 64
  # 40G.

  # batch_size: 256 # being run on A100 with 80G memory. No need for multinode.